[package]
authors = ["itang <live.tang@gmail.com>"]
name = "rust_rocket_version"
version = "0.1.0"

[dependencies]
redis = "0.8.0"
rocket = "0.2.7"
rocket_codegen = "0.2.7"
rocket_contrib = "0.2.7"
serde = "0.9.15"
serde_derive = "0.9.15"
serde_json = "0.9.10"
time = "0.1.36"
