refresh_rate = "5 seconds"

[appenders.console]
kind = "console"

[appenders.console.encoder]
pattern = "{d(%+)(local)} [{t}] {h({l})} {M}:{m}{n}"

[[appenders.console.filter]]
kind = "threshold"
level = "error"

[appenders.file]
kind = "file"
path = "logs/application.log"
pattern = "{d} [{t}] {l} {M}:{m}{n}"

[root]
level = "info"
appenders = ["console", "file"]

[loggers."test::a"]
level = "info"
appenders = ["file"]
additive = true
