[package]
authors = ["itang <live.tang@gmail.com>"]
name = "rustversion"
version = "0.1.0"

[dependencies]
bodyparser = "0.4.1"
iron = "0.4.0"
redis = "0.7.0"
router = "0.2.0"
serde = "0.8.4"
serde_json = "0.8.1"
serde_macros = "0.8.4"
time = "0.1.35"
